In [3]:
a = [1,2,3,4]
b = [5,6,7,8]
c = [9,10,11]

zip1 = zip(a,b) 
print(zip1) #only display as zip object <zip object at 0x000002C707F5DF00>

print(tuple(zip1)) #((1, 5), (2, 6), (3, 7), (4, 8))  - zip can only be displayed this way

tuple1 = tuple(zip1)
print(tuple1)     # Note: prints ().  

((1, 5), (2, 6), (3, 7), (4, 8))
()


In [4]:
zip2 = zip(a,c)
print(tuple(zip2)) # note: zip only zip uptill the lower size -- c only has 3 members.

((1, 9), (2, 10), (3, 11))


In [1]:
# but tuple is troublesome as you cant edit them.
a = [1,2,3,4]
b = [5,6,7,8]
c = [9,10,11]

zip1 = zip(a,b) 

print('list(zip1):\n',list(zip1))  # note: sometimes prints [].

print('\nlist(zip(a,b)):\n',list(zip(a,b)))  # printing the list of zip directly, works the best!!

import numpy as np
print('\nnp.array(zip(a,b)):\n',np.array(zip(a,b)))  # prints <zip object at 0x000002C707FF7EC0>, cannot convert to ndarray

print('\nnp.array(list(zip(a,b))):\n',np.array(list(zip(a,b))))  # have to do this way to convert to ndarray!!

list(zip1):
 [(1, 5), (2, 6), (3, 7), (4, 8)]

list(zip(a,b)):
 [(1, 5), (2, 6), (3, 7), (4, 8)]

np.array(zip(a,b)):

np.array(list(zip(a,b))):
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [9]:
# if have numpy array, best to use np methods to do concat
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11])

x1 = np.stack((a,b),axis=0)
print(x1)
x2 = np.stack((a,b),axis=1)
print(x2)

#x1 = np.stack((a,c),axis=0) # shape of a,c different, so cannot stack

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[[ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]
  [ 4  8 12]]]
